from pydantic import BaseModel, Field, model_validator
from datetime import datetime
from typing import Optional

class UserProfile(BaseModel):
    user_id: str  # The UUID generated by the Flutter client
    age: int
    height: float
    weight: float
    bmi: float = 0.0
    marital_status: Optional[str] = "single"
    family_history: bool = False
    # Server-side tracking
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)

    @model_validator(mode="after")
    def calculate_bmi(self):
        if self.height and self.weight:
            height_m = self.height / 100
            self.bmi = round(self.weight / (height_m ** 2), 2)
        return self