from pydantic import BaseModel, Field, validator
from datetime import datetime
from typing import Optional

class UserProfile(BaseModel):
    user_id: str  # The UUID generated by the Flutter client
    age: int
    height: float
    weight: float
    bmi: float = 0.0
    marital_status: Optional[str] = "single"
    family_history: bool = False
    # Server-side tracking
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)

    @validator('bmi', pre=True, always=True)
    def calculate_bmi(cls, v, values):
        height = values.get('height')
        weight = values.get('weight')
        if height and weight:
            height_m = height / 100
            return round(weight / (height_m ** 2), 2)
        return v