// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCW_aSnWbFuc75Sp8F2dUs_hwifrstrK9E',
    appId: '1:895935152452:web:50f7dd84cf46c1711b5711',
    messagingSenderId: '895935152452',
    projectId: 'shehealth-f67a5',
    authDomain: 'shehealth-f67a5.firebaseapp.com',
    storageBucket: 'shehealth-f67a5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQU5f6FJl7xbQ1BuyQFushsEkRZ5ncjLU',
    appId: '1:895935152452:android:74df3828e34a2d9a1b5711',
    messagingSenderId: '895935152452',
    projectId: 'shehealth-f67a5',
    storageBucket: 'shehealth-f67a5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxwXL1G-uWuQ2uFiC2ibkutD11120NVD4',
    appId: '1:895935152452:ios:55397a2a50b0a27f1b5711',
    messagingSenderId: '895935152452',
    projectId: 'shehealth-f67a5',
    storageBucket: 'shehealth-f67a5.firebasestorage.app',
    iosBundleId: 'com.example.shehealth',
  );
}
